[package]
name = "macros"
version = "1.0.0"
authors = ["Alan Boyd"]
edition = "2021"

[dependencies]

syn = { version = "*", features = ["extra-traits"] }
quote = "*"
proc-macro2 = "*"

[lib]
name = "macros"
path = "lib.rs"
proc-macro = true

[features]

